UPDATE marketing_prospect
SET status = 'new', statuses = '["new"]', updated_at = (strftime('%s','now') * 1000)
WHERE status = 'letter_sent' AND lower(trim(name)) IN (
  'jersey sea sport centre',
  'royal channel islands yacht club',
  'stowaway sailing jersey',
  'the variety sailing trust',
  'le mourier',
  'st catherine''s sailing club',
  'st helier yacht club',
  'tony cavey training centre',
  'bourne to sail',
  'jono''s watersports',
  'shanklin sailing club',
  'ventnor yacht club',
  'yacht tutor',
  'bembridge powerboat training ltd',
  'buzz active',
  'eastbourne sovereign sailing club',
  'sovereign harbour bertholders association',
  'yaverland sailing & boat club',
  'newhaven yacht club',
  'pevensey bay sailing club',
  'seahaven maritime academy - newhaven',
  'sovereign harbour yacht club',
  'bexhill sailing club',
  'brighton boating',
  'brighton marina yacht club',
  'hatt adventures',
  'waterfront sailing academy',
  'action watersports',
  'kent & sussex powerboat training',
  'rye harbour sailability',
  'rye harbour sailing club',
  'atlantic marine training',
  'newquay sailing club',
  'varne boat club ltd',
  'west galway school of navigation',
  'camel powerboat centre',
  'padstow sailing club',
  'rock sailing & water ski club',
  'wadebridge boating club',
  'kernow training',
  'looe sailing club',
  'quay sailing club',
  'take a turn yachting',
  'commercial diver training ltd',
  'fowey maritime centre',
  'royal fowey yacht club',
  'sunny side sailing',
  'weir quay sailing club',
  'cargreen yacht club',
  'rnsa west country',
  'tamar river sailing club',
  'torpoint mosquito sailing club',
  'babbacombe corinthian sailing club',
  'horizons (plymouth)',
  'millbrook lake mooring association',
  'porthpean sailing club',
  'start point sailing',
  'disabled sailing association',
  'seasports southwest ltd',
  'shaldon sailing club',
  'teign corinthian yacht club',
  'brixham junior sailing club',
  'grenville house oec',
  'newton abbot sailing club',
  'andrew simpson watersports centre - portland',
  'cockwood boat club',
  'sirius business services ltd',
  'stoke gabriel boating association',
  'vigilance of brixham cio',
  'chesil sailability',
  'jurassic aqua sports',
  'osprey training centre',
  'weymouth powerboat training centre',
  'royal dorset yacht club',
  'sea cadets uk',
  'sprites sea school',
  'weymouth sailing',
  'bh marine academy llp',
  'lyme bay sea school',
  'neat',
  'redclyffe yacht club',
  'royal solent yacht club',
  'aquasafe powerboat school',
  'hurst castle sailing club',
  'keyhaven yacht club ltd',
  'salterns sailing club',
  'west solent sea school',
  'lymington sailability',
  'lymington yacht charters & sea school',
  'missisle school of sip-puff sailing',
  'the rib school limited',
  'arun youth aqua centre',
  'bognor regis yacht club',
  'medina mariners association',
  'mudeford sailing club',
  'arun yacht club',
  'pagham lagoon sailing',
  'pagham yacht club',
  'seahorse marine school',
  'starlight coaching'
);
