/**
 * The Learning Centre's content: one source for the /learn page and the help
 * assistant (lib/help), so the two can never drift apart. Every user-facing
 * feature ships with a section here (CLAUDE.md).
 */

/** A block of guide content. */
export type Block =
  | { kind: "p"; text: string }
  | { kind: "steps"; items: string[] }
  | { kind: "bullets"; items: string[] }
  | { kind: "tip"; text: string }
  | { kind: "sub"; text: string }
  | { kind: "providerHelp" };

export interface Section {
  id: string;
  icon: string;
  label: string;
  blurb: string;
  blocks: Block[];
}

export const SECTIONS: Section[] = [
  {
    id: "getting-started",
    icon: "🚀",
    label: "Getting started",
    blurb: "Set your centre up in a few minutes with the guided wizard.",
    blocks: [
      { kind: "p", text: "When you first sign in you land on the onboarding wizard. It only asks for what it needs to get you rostering — everything else can wait." },
      { kind: "sub", text: "The five steps" },
      { kind: "steps", items: [
        "How you run — pick the extra features you want (equipment, locations, operating areas, payroll, info) and choose whether your sessions run as Morning/Afternoon/Evening slots or with explicit start & end times.",
        "Courses — tick the RYA courses you offer (grouped by youth and adult), or add your own. Use “Add all RYA courses” if you run a lot of them.",
        "Team — add each instructor, tick the qualifications they hold and the courses they can teach, and add their email to send an invite.",
        "Roster PDF — choose what your printable roster shows (times, staff, students, locations, equipment), its style and whether it is portrait or landscape. You can change it later under Settings.",
        "Finish — you're ready to roster. Any optional features you switched on appear here with a “set up” link.",
      ] },
      { kind: "tip", text: "You can leave the wizard at any time with “Skip for now”. The dashboard keeps a checklist so you can finish setup later." },
      { kind: "sub", text: "Instructors under 18" },
      { kind: "p", text: "Every staff profile has a date of birth. Anyone under 18 is flagged automatically (the flag lifts on their 18th birthday), and their profile gains a parent or guardian contact plus a slot for the signed parental permission to work. Phone numbers and emails of under-18s are shown only to centre admins and the welfare officer; colleagues see names and shift times unless the young person chooses to share their contact details. A parent or guardian can be given a read-only view of their roster. Every staff member also has an emergency contact, stored encrypted and visible to admins only, with each view written to your change log." },
      { kind: "sub", text: "Your privacy notice" },
      { kind: "p", text: "You are the data controller for your staff's details; ActivityRoster processes them for you. Add a link to your own privacy notice under Office → Settings and it appears beside ours for every member of your team. Need wording? We publish a template notice for staff and a plain-English version for under-18 instructors in our documentation; ask us for a copy." },
      { kind: "sub", text: "Coming back to sign in" },
      { kind: "p", text: "Your centre lives at its own address, yourcentre.activityroster.com, and you can bookmark it. You never need to remember it, though: the Sign in link on the homepage asks only whether you run a centre or work at one, then takes your email and password. Your email tells us which centre you belong to; if you belong to more than one, you choose after signing in." },
      { kind: "p", text: "Centre admins sign in with email and password. The first time on a device, and again after that device has gone 12 hours without using the office, we email a 6-digit code to enter (if you've turned on two-factor, that step counts instead; arriving from an invitation or emailed sign-in link counts too, since the link already proved your email). Then you choose whether to stay signed in on that device. Pick \"just this once\" on a shared computer and you're signed out when the browser closes. You're asked for your 4-digit PIN after 30 minutes without activity, and after 12 hours away you sign in again from the start." },
    ],
  },
  {
    id: "settings",
    icon: "⚙️",
    label: "Settings & configuration",
    blurb: "Tune courses, roles, checks and how sessions run.",
    blocks: [
      { kind: "p", text: "Settings is where you adjust the defaults you set during onboarding. It is split into tabs: General (company code, warnings, the checks applied when rostering, the availability window, holiday pay), Roster & welfare (welfare officers, the roster PDF, course default schedules), Time & pay, Lists (slots, roles, certs, checks) and Data & account (retention, export, billing, security, PIN). Switching off a safety check asks you to confirm and names what will no longer be stopped." },
      { kind: "bullets", items: [
        "Activate or retire course types, qualification/instructor types and compliance checks — retired items keep their history and stop appearing for new records.",
        "Switch optional features on or off.",
        "Change how sessions run (slots vs explicit times) and your alert lead time for expiries.",
        "Lunch breaks: set the break length, after how many hours it applies, and whether it's paid. Payroll uses this.",
      ] },
      { kind: "sub", text: "Course default schedule" },
      { kind: "steps", items: [
        "In Settings → Course default schedule, click Set next to a course type.",
        "Add each session: which day of the course (Day 1, Day 2…) and its start and end times. A two-day course might be Day 1 09:00–17:00 and Day 2 09:00–17:00.",
        "Save. Now, when you pick that type in “Add a course”, choose a start date and click “Fill sessions”. Every session is filled in for you, and you can still change any of them.",
      ] },
      { kind: "tip", text: "Configuration is deactivate-never-delete: old records keep pointing at retired settings and still render correctly." },
    ],
  },
  {
    id: "locations",
    icon: "📍",
    label: "Locations & areas",
    blurb: "Organise your sites, classrooms and operating areas.",
    blocks: [
      { kind: "p", text: "The Locations tab lets you add the places you run from and group them into categories (e.g. “On the water”, “Classrooms”, “Off-site”)." },
      { kind: "steps", items: [
        "Add a location.",
        "Put it in a category — or add your own category if none fits.",
        "Attach locations to courses so they appear on the roster.",
        "Rename or retire a category from its box header; retired categories can be brought back from the list at the bottom.",
      ] },
    ],
  },
  {
    id: "equipment",
    icon: "⛵",
    label: "Equipment & boats",
    blurb: "Track boats, yachts, engines and kit — and avoid clashes.",
    blocks: [
      { kind: "p", text: "If you switched on equipment tracking, the Equipment tab lets you record your fleet and kit by type — dinghies, keelboats, yachts, motor cruisers, coach/safety boats, SUPs and more." },
      { kind: "bullets", items: [
        "Manage your equipment types at the top of the Equipment tab — rename them, set how many of each you have (e.g. 12 Pico dinghies), and mark each as tracked or bulk.",
        "Attach tracked units or bulk quantities to a course when you create it, or later from the course page (“Where & what”).",
        "The problems list flags a unit booked on two overlapping sessions, a unit in maintenance that is still on a course, and a day when the courses running need more of a type than you own (Settings → General switches that last check off).",
        "Bulk (untracked) kit doesn't clash by unit; its quantities still count against what you own.",
        "Delete removes a unit or type that nothing has ever used; anything a course used is retired instead and kept in a collapsed “Retired” section, still showing on old courses. The same rule applies to locations, course types and instructors.",
      ] },
      { kind: "sub", text: "Warnings while you pick" },
      { kind: "p", text: "On a course's “Where & what”, a unit already on another course at the same time is marked, and bulk kit shows when the courses running at the same time would need more than you own. Saving still works (plans change on the beach), and the save message repeats any clash or shortage." },
      { kind: "sub", text: "In maintenance" },
      { kind: "p", text: "When a unit is in maintenance you can say why (for example “outboard”) and when it should be back. The problems list then reads “Safety boat 2 is in maintenance (outboard), back 14 Oct”. Setting it back to Available clears both. A line at the top of the page counts each type, for example “Picos: 12 (10 available, 2 in maintenance)”." },
      { kind: "sub", text: "Kit rules (off unless you switch them on)" },
      { kind: "p", text: "Under Course setup you can say what kit each kind of course needs: a fixed number (1 safety boat) or a number per so many students (1 Pico per 2 students, rounded up). Tick Settings → Checks when rostering → “Use kit rules” and every new course gets that kit automatically for the students booked, and a course page offers the suggestion when it has no bulk kit yet. You can always change a course's kit by hand." },
      { kind: "tip", text: "Equipment isn't gated — if it's not switched on you'll see a notice on the page with a one-click option to turn it on." },
    ],
  },
  {
    id: "courses",
    icon: "📅",
    label: "Courses & sessions",
    blurb: "Build a course with any pattern of sessions across days and times.",
    blocks: [
      { kind: "p", text: "Open Courses. At the top is the planner: a week calendar plus a builder. A course is one thing (e.g. “Aug Half-Term Kids Camp”) made of one or more sessions on whatever days and times you like." },
      { kind: "sub", text: "Create a course" },
      { kind: "steps", items: [
        "Give it a name (optional but recommended — it makes the course unique and easy to find).",
        "Pick the course type (this sets the RYA scheme, ratios and whether safety cover is required).",
        "Add sessions — click a day in the calendar, or use “＋ Add session”. Add as many as you need: e.g. two on Saturday, one Monday evening, one Wednesday.",
        "For each session set the slot (Morning/Afternoon/Evening), or tick “Exact times” to set a precise start & end.",
        "Open “More options” if you want to say who's needed (e.g. 2× Instructor and 1× Safety Boat) or tick the locations and equipment the course uses — all optional.",
        "Click “Create course”.",
      ] },
      { kind: "sub", text: "Staffing one day differently" },
      { kind: "p", text: "People are put on the whole course by default. On a multi-day course you can change a single day: on the course page each session lists who's on it, with “skip this day” next to anyone who isn't needed that day and “+ add for this day” for one-day cover. Open shifts are filled this way too, so cover for one session never puts someone on the whole week. The roster, the PDF, the emergency sheet, payroll and the app all follow." },
      { kind: "sub", text: "Staffing: one panel" },
      { kind: "p", text: "Each course has a single Staffing panel (on the course page, and under 👥 on the course card). Enter the students booked; it shows what the RYA ratio from the course type implies and can suggest the roles. Adjust the role lines (say, 2 × Instructor and 1 × Safety boat) and the number of staff needed follows from them. If the lines fall short of the ratio, the panel says so." },
      { kind: "sub", text: "When two of you are editing" },
      { kind: "p", text: "If someone else changes a course's staffing, locations or kit after you opened the page, your save is stopped with a note saying who changed it and when, rather than quietly undoing their change. Reload, check what they did, then make yours. Pay lines on the payroll page work the same way. If two of you put the same person on two overlapping courses at the same moment, the second booking is taken back out and you're told. Saves are all or nothing: if the connection drops part-way, nothing has changed and you can simply try again." },
      { kind: "sub", text: "Manage a course" },
      { kind: "bullets", items: [
        "Open a course to rename it, change its status (draft, scheduled, confirmed, completed, cancelled), set how many students are booked (this drives the ratio check), add or remove sessions, and assign instructors.",
        "The search box above the list finds a course by its name or type, in Upcoming or Past.",
        "If your course list is ever empty (everything unticked in the setup wizard), the Courses page offers “Restore RYA courses” to bring the standard list back.",
        "Each course card shows its audience (youth/adult), the date/times of its sessions, and its staffing status (covered / under-staffed / no safety cover).",
        "Open a course card to see each role it needs and how many are filled, e.g. “Instructor 1/2”.",
      ] },
      { kind: "sub", text: "Course types: your regular list vs one-offs" },
      { kind: "bullets", items: [
        "The course-type dropdown shows only your regular list — the types you run all the time.",
        "Running something unusual? Pick “＋ Other (type it in)…” and type the name. It's a one-off and stays off your list, unless you tick “Add to my regular course list”.",
        "Course setup lists one-off types separately. Click “Add to list” to make one regular, or “Move courses to…” to file its courses under an existing type and remove the duplicate.",
      ] },
      { kind: "tip", text: "Deleting a course removes its sessions, staff assignments, equipment and location links too — so you don't leave orphans behind." },
    ],
  },
  {
    id: "import",
    icon: "📥",
    label: "Importing courses",
    blurb: "Bring your existing schedule in from a spreadsheet or calendar.",
    blocks: [
      { kind: "p", text: "On the Courses page use “Import from spreadsheet / calendar”. You can paste or upload a CSV, or an .ics calendar file." },
      { kind: "steps", items: [
        "Upload or paste your data.",
        "We detect the columns (course, date, time, audience) automatically and turn each row into a draft session.",
        "Review the drafts — anything uncertain is flagged so you can correct it before it's saved.",
        "Check the Type column. Booking systems rarely use exactly your names, so we match each course to your closest course type (e.g. “RYA Stage 1 – Summer Week” → Youth Stage 1). Anything marked “no match” you can file under the right type, add to your list, or keep as a one-off.",
        "Confirm to create the courses and sessions.",
      ] },
      { kind: "tip", text: "Import is a great way to move a season's worth of courses over in one go instead of typing them in one by one." },
    ],
  },
  {
    id: "integrations",
    icon: "🔌",
    label: "Booking system integrations",
    blurb: "Pull your courses in from the booking system you already use — whenever you press the button.",
    blocks: [
      { kind: "p", text: "If you already take bookings in another system, ActivityRoster can pull your courses in so you never re-type them — only when you press “Check for updates”, never on a schedule. Open Office → Courses → “Connect a booking system” (or the Integrations page)." },
      { kind: "sub", text: "How it works" },
      { kind: "steps", items: [
        "Pick your booking system from the list (WebCollect, Bookwhen, Eola, Class4Kids, Checkfront and more — or any calendar).",
        "Paste its calendar (iCal) feed URL — each system shows you where to find this; the page gives per-system hints. Some (e.g. Bookwhen) can connect with an API key instead.",
        "Whenever you want, hit “Check for updates”. We compare the feed with your platform and show you what's changed — nothing is imported or deleted until you say so.",
        "Review the changes and Apply.",
      ] },
      { kind: "sub", text: "You're always in control" },
      { kind: "bullets", items: [
        "It's one-way and read-only — we never change anything in your booking system.",
        "“Check for updates” shows two lists: new courses in the feed to add, and courses you imported before that have been removed from the feed.",
        "New courses are pre-ticked to add; removed courses are never pre-ticked — nothing is deleted unless you tick it. You can also Edit a course instead.",
        "Each new course is matched to one of your course types, so you don't end up with near-duplicates. Check the type next to each one before applying — change it, add the name to your list, or keep it as a one-off.",
        "Only future sessions are considered; past events are ignored, and manually-created courses are never touched.",
        "It's manual on purpose — updates happen when you press the button, not on a hidden schedule.",
      ] },
      { kind: "sub", text: "Where to find your feed link, by system" },
      { kind: "p", text: "Every booking system keeps its calendar (iCal) feed URL in a slightly different place. Here's exactly where to look in each — copy that link and paste it on the Integrations page." },
      { kind: "providerHelp" },
      { kind: "tip", text: "No calendar feed? Export a spreadsheet from your system and use “Import from spreadsheet / calendar” instead — same result." },
    ],
  },
  {
    id: "staff",
    icon: "👥",
    label: "Instructors & team",
    blurb: "Add instructors, job types and the courses they can teach.",
    blocks: [
      { kind: "p", text: "The Instructors tab lists everyone at your centre with their status and whether they're cleared to roster." },
      { kind: "sub", text: "The quick way" },
      { kind: "p", text: "Under Add instructors, Quick add takes just a name and an email, with “Send the invite” ticked: they fill in their own phone, date of birth and certificates from the invite. For the start of the season, Paste a list takes one person per line as copied from an email or spreadsheet (“Sam Jones, sam@example.org” or “Kim Lee <kim@example.org>”); it shows how many it found before you add them. People without an email are added but not invited." },
      { kind: "sub", text: "Add an instructor with all details" },
      { kind: "steps", items: [
        "Open “Add with all details”, then enter their name and (optionally) email.",
        "Pick their employment type — employed, freelance or volunteer. Need a different one? Add a custom job/instructor type inline.",
        "Tick the qualifications/licences they hold and the courses they can teach (a searchable tickbox list).",
        "Save. If you gave an email, they're automatically invited to the instructor app to upload their own certs.",
        "An invite shows as “Invited today”, “Invited 3 days ago” and so on until they open it. Access to your centre only starts when the invited person signs in, so a mistyped address can't let the wrong account in.",
        "The invitation email names your centre and who sent it, and lists what to do first. If they haven't signed in a day later, they get one reminder, and nothing more. “Re-send invite” sends a fresh one and starts that day again.",
      ] },
      { kind: "sub", text: "Courses each person can teach" },
      { kind: "p", text: "Each staff profile shows the courses they're approved to teach. This drives the fit checks when you roster — and you can see it at a glance on their profile." },
      { kind: "sub", text: "Reminding people" },
      { kind: "bullets", items: [
        "The list shows whether each person has set their availability and whether any licence or check needs updating.",
        "Press Remind on a row to send that person a notice in the app (with a phone notification) and an email: to mark when they're free, or listing the licences that are missing, expired or running out.",
        "“Everyone who hasn't set availability” and “Everyone who needs a licence update”, above the list, remind them all at once after you confirm.",
        "Each person gets at most one reminder of each kind a day, however often it's pressed. People who haven't signed up need an invite before an availability reminder can reach them; people whose availability the office keeps are never asked.",
      ] },
    ],
  },
  {
    id: "staff-import",
    icon: "📇",
    label: "Importing instructors",
    blurb: "Bring your whole team in from a spreadsheet — even a rough, incomplete one.",
    blocks: [
      { kind: "p", text: "On the Instructors tab use “Import from spreadsheet”. Your list doesn't need to be tidy or complete — the only thing every row needs is a name." },
      { kind: "steps", items: [
        "Paste your list or upload a CSV.",
        "Match your columns — we guess them, you correct any that are wrong. Name is the only required column.",
        "Review every row: fix names/emails, and see any flags (e.g. missing email means no invite yet).",
        "Optionally tick “email a portal invite to everyone with an email”, then import.",
      ] },
      { kind: "sub", text: "How messy data is handled" },
      { kind: "bullets", items: [
        "Rows without a name are skipped, never guessed.",
        "Qualifications/licences and courses-they-can-teach are matched to your catalogue by name; anything it doesn't recognise is ignored so you don't get junk — add those on each profile later.",
        "Employment type is read loosely (e.g. 'casual' → freelance) and defaults to employed.",
      ] },
      { kind: "tip", text: "Start simple: a sheet of just names and emails is enough to get everyone in and invited — you can fill in certs and courses afterwards." },
    ],
  },
  {
    id: "roles",
    icon: "🔑",
    label: "Who can do what",
    blurb: "Superadmin, office admins with their own feature set, instructors and parents.",
    blocks: [
      { kind: "p", text: "There are four kinds of user in a centre. Nobody needs more than one account: a Chief Instructor who also teaches has an office login and an instructor record." },
      { kind: "bullets", items: [
        "Superadmin — the person who set the centre up and pays for it. One per centre; can do everything, including giving office access. To hand it to someone else, contact ActivityRoster support.",
        "Office admin — uses the office. The superadmin ticks which parts each office admin can reach, under Instructors → Office access: Roster & courses, Staff, Emergency & guardian contacts, Payroll, Settings, Billing, Exports & data tools. A new office admin starts with none ticked.",
        "Instructor — the instructor app: shifts, availability, confirmations, certs and hours. Senior instructors and volunteers are instructors too; “senior” is a qualification, not access.",
        "Parent / guardian — a read-only view of their under-18 child's roster, and the parental permission answer. When a young person signs up in the app and their date of birth shows they are under 18, they give a parent's email; the parent is emailed, makes a small account and approves or declines. Until a parent approves, the office can't roster them (an admin can override with a note). Settings → Young workers switches the requirement off.",
      ] },
      { kind: "p", text: "Sensitive pages say who can open them, by name: payroll, certs and documents, emergency and guardian contacts, the emergency sheet and the whole-centre export each show a line like “Visible to Conor (superadmin) and Ellie (Payroll)”, with a link to change it. The emergency sheet always shows who is on duty, but the emergency and guardian contacts on it need the Emergency & guardian contacts tick. If an office admin follows a link to a part they can't reach, the dashboard tells them which tick they need and who to ask." },
      { kind: "p", text: "A welfare officer isn't an account: under Settings you list your welfare officers by name and, if you like, who is on duty by default on each day and slot. The roster can then show “Welfare on duty” beside each session, like locations and equipment." },
      { kind: "sub", text: "Contact details between colleagues" },
      { kind: "p", text: "Colleagues see names and shift times only. An instructor who is happy to be contactable can switch on “Let colleagues see my phone and email” in their portal settings; they then appear in the Team contacts list in everyone's portal. Under-18s are never offered this." },
      { kind: "sub", text: "Parent or guardian access" },
      { kind: "p", text: "For an instructor under 18, an admin can invite the parent or guardian on file to a read-only view of the young person's roster: dates, courses, times and places, nothing else and nobody else's details. The consent the centre holds (for example “signed permission form on file”) is recorded with the invitation and shown to the guardian. Remove access from the same card at any time; it ends automatically when the profile is anonymised." },
    ],
  },
  {
    id: "licences",
    icon: "🎫",
    label: "Certs & vetting",
    blurb: "Track every cert and check, with expiry alerts.",
    blocks: [
      { kind: "p", text: "Every instructor has a document area for their qualifications (dinghy, keelboat, windsurf, SUP, powerboat, first aid…) and their checks (DBS, safeguarding, first aid)." },
      { kind: "p", text: "Vetting checks (DBS, PVG, AccessNI, Garda) are different: the centre records the status, the certificate number and the dates, and marks the check verified once it has seen the certificate. The certificate itself is never uploaded or stored, and the number is encrypted. That keeps the most sensitive document out of the system entirely. The built-in vetting checks are already marked this way; if you add your own check type under Settings → Checks, tick “Vetting check” and it is treated the same." },
      { kind: "sub", text: "Two ways to add documents" },
      { kind: "bullets", items: [
        "The instructor uploads their own: they pick the cert from a dropdown, add a photo/scan and the expiry date.",
        "The office uploads on their behalf and can edit the expiry, add a reference/certificate number, and mark it verified.",
      ] },
      { kind: "sub", text: "Expiry alerts" },
      { kind: "p", text: "Anything expiring within your lead time is flagged on the dashboard and the staff list. Instructors are reminded in the app and by email, and every Monday admins get one email listing what has expired or is about to. Expired mandatory checks stop an instructor being rostered until they're renewed." },
      { kind: "tip", text: "“Not cleared to roster” always shows the actual reason (e.g. “DBS missing”, “First Aid expired”) rather than a vague label." },
    ],
  },
  {
    id: "app",
    icon: "📱",
    label: "The instructor app",
    blurb: "ActivityRoster on the App Store and Google Play — your roster, hours and certs in your pocket.",
    blocks: [
      { kind: "p", text: "Instructors and volunteers use the free ActivityRoster app (iPhone and Android). Everything in the instructor portal is in it — schedule, availability, clock in/out, leave, hours, documents — plus phone notifications, Face ID / fingerprint unlock and a camera button for cert photos." },
      { kind: "sub", text: "No signal on the beach" },
      { kind: "p", text: "Each time you open My schedule with a signal, the next seven days are saved on your phone. If the schedule can't load later, you see that saved week instead, with the time it was saved. Signing out removes it from the phone. Face ID or fingerprint unlocks the app in place of typing your PIN (Settings → App), and the PIN is always there as the fallback." },
      { kind: "sub", text: "Shifts in your own calendar" },
      { kind: "p", text: "In the app, Settings → Calendar → “Make my calendar link”, then “Add to my calendar” (or Google Calendar). Published shifts appear in the phone's own calendar with the course, your role, the time and the place, and update about every hour. The link is private and shown only once; “Make a new link” replaces it and the old one stops working, and “Turn off” stops it entirely. It never contains colleagues' names or contact details." },
      { kind: "sub", text: "Your company code" },
      { kind: "steps", items: [
        "Open Settings → “Company code · instructor app”. Each centre has its own 6-character code — copy it and share it with your team (a notice board, a WhatsApp group, your welcome email).",
        "If a code leaks, press “Issue a new code”. The old one stops working immediately; people already joined are unaffected.",
      ] },
      { kind: "sub", text: "How an instructor joins" },
      { kind: "steps", items: [
        "Install the app and tap “Create your account”: name, mobile number, email and a password.",
        "Enter the 6-digit code we email them to confirm the address, then choose a 4-digit PIN.",
        "Type in your company code. If their email is already on your Instructors list, they're in straight away. If not, they appear under Instructors → Join requests for you to approve or decline — so a leaked code never lets a stranger in.",
        "Works for more than one centre? They join each with its code and switch between them in the app's Settings.",
      ] },
      { kind: "sub", text: "What the app adds" },
      { kind: "bullets", items: [
        "Phone notifications for roster changes, new open shifts, leave decisions and expiring certs (they can switch these off).",
        "One-tap “I'll be there” on each published course — or “Can't make it” with a reason, so the office can find cover. Colleagues, student numbers and the location show once the week is published.",
        "Availability has “Same as last week”, “All free” and “Clear week” so a regular pattern takes two taps.",
        "Settings: update your name and mobile number, change your PIN, and set or change your password. Docs has a Replace button for a renewed cert.",
        "Face ID / fingerprint instead of typing the PIN every time; the PIN stays as the fallback.",
        "Clock in and out records an approximate location — shown as a 📍 map link on your Time clock page.",
        "A camera button on Documents to photograph a certificate straight into their record.",
      ] },
      { kind: "tip", text: "The web portal keeps working exactly as before — the app and the web are the same account." },
    ],
  },
  {
    id: "availability",
    icon: "🗓️",
    label: "Availability",
    blurb: "Collect availability and see it before you build the roster.",
    blocks: [
      { kind: "p", text: "Instructors answer from their own app: Free, Maybe or Busy for each Morning/Afternoon/Evening slot. There is no blank: inside your availability window a slot counts as Busy until it's marked Free or Maybe, so nobody is rostered on a guess." },
      { kind: "sub", text: "The usual week and day notes" },
      { kind: "bullets", items: [
        "Each instructor can set a usual week once (say, Free every Saturday and Sunday). It fills in any day they haven't answered, and they only change the exceptions.",
        "They can leave a short note against a day (“back by 2pm”), which the office sees in the grid.",
        "Approved leave is written into availability as Busy automatically.",
      ] },
      { kind: "sub", text: "The availability sheet" },
      { kind: "bullets", items: [
        "The office sees a grid of everyone's availability for the week, with a count of how many are free in each slot. Grey Busy means they haven't answered; “usual” means it came from their usual week.",
        "A switch at the top picks what clicking does. Assign staff (the default): click a free slot to see the sessions that person can do then, and assign them. Nothing in the grid changes by accident.",
        "Edit availability: change who's free, recorded as set by the office (ideal for volunteers who don't use the app).",
        "A navy dot shows where someone is already rostered, so you can see availability and commitments together.",
      ] },
      { kind: "sub", text: "The availability window" },
      { kind: "p", text: "Settings → General sets how many weeks ahead instructors are asked (4 by default, up to 26). Beyond the window nobody has been asked yet, so nothing blocks rostering there; the roster and the availability sheet show a note with a link to lengthen it." },
      { kind: "sub", text: "Editing availability: two ways" },
      { kind: "bullets", items: [
        "A whole week or day at once: in Edit availability, click a person's name to set their whole week, a day heading to set everyone that day, or AM / PM / EV to set everyone in that slot, then pick Free, Maybe or Busy. “Everyone, this whole week…” sets every active person (it asks first).",
        "Slot by slot: pick Free, Maybe, Busy or Clear, then click or drag across slots to paint them. Each stroke saves in one go. Press “stop painting” when you're done.",
        "With nothing picked, clicking one slot opens it so you can set just that slot.",
        "Approved leave is never overwritten: those slots stay Busy.",
      ] },
      { kind: "tip", text: "The number under each slot tells you how many instructors are free then — handy before you start assigning. Running availability from the office, with no staff sign-up? See “Run it from the office”." },
    ],
  },
  {
    id: "office-managed",
    icon: "🏢",
    label: "Run it from the office (no staff sign-up)",
    blurb: "Use ActivityRoster without instructors signing up: the office keeps everyone's availability.",
    blocks: [
      { kind: "p", text: "Some centres don't want every instructor on an app, or have volunteers who never will be. Choose “The office” and ActivityRoster works without anyone signing up: you keep availability, build the roster and publish it, and staff hear about their sessions by email." },
      { kind: "steps", items: [
        "Settings → General → “Who keeps staff availability up to date?” → choose “The office. Staff don't need to sign up.” and save.",
        "Add your staff in Staff (a name is enough; email is optional, and no invite is sent unless you tick it).",
        "Everyone now counts as free unless you mark them busy. On the Availability page, paint the days people can't work with the Busy brush, or set each person's usual week on their page.",
        "Roster as normal. Office-managed people are recorded as confirmed straight away; nobody is asked to confirm.",
        "Publish the week. Everyone with an email gets a list of their sessions; anyone with no app and no email is named so you can hand them the printed roster.",
      ] },
      { kind: "sub", text: "On each staff member's page" },
      { kind: "bullets", items: [
        "Availability card: who keeps their availability (the centre's setting, the person in the app, or the office), their usual week, and the next four weeks to paint with a brush.",
        "“Office-managed · no sign-up needed” shows at the top for anyone the office looks after who hasn't signed up.",
        "You can still invite anyone who wants the app. They'll see their roster there and can mark days they can't work, and they still count as free unless marked busy.",
      ] },
      { kind: "sub", text: "Mixing the two" },
      { kind: "p", text: "The setting is centre-wide, but each person can be set differently on their page: for example, staff keep their own availability in the app, while a few volunteers without smartphones are kept by the office." },
      { kind: "tip", text: "Under-18s still need parental approval and still get the young-workers' hours checks, however their availability is kept." },
    ],
  },
  {
    id: "dashboard",
    icon: "📊",
    label: "Dashboard & calendar",
    blurb: "Your week at a glance — the visual heart of the platform.",
    blocks: [
      { kind: "p", text: "The dashboard opens on today: a Today strip with the sessions running, how many people are on, what's uncovered, who can't make it and today's problems, with a link to the emergency sheet. Below it: quick tiles (on the water now, hours logged, sessions this week) and anything needing attention (staff not cleared, checks expiring, courses to cover, leave to approve, open shifts, problems on the roster)." },
      { kind: "sub", text: "The week calendar" },
      { kind: "p", text: "Below the tiles is a colour-coded week calendar — youth courses in amber, adult in teal. Use the ← → buttons to move between weeks, or “This week” to jump back. Click any course block to open it. On a phone the calendar starts folded so the useful parts come first." },
      { kind: "sub", text: "This week's roster" },
      { kind: "p", text: "Under the calendar is the written roster for the week — every session, who's on it, where and when — with a link to the full printable roster." },
      { kind: "tip", text: "The “＋ New course” button on the calendar takes you straight to the course planner." },
    ],
  },
  {
    id: "board",
    icon: "🗂️",
    label: "The roster board",
    blurb: "Build and fix the week on one screen: courses by day, or people across days.",
    blocks: [
      { kind: "p", text: "The Roster page is where the week is built. “Courses by day” shows each day's sessions as cards with who's on them and the roles still open; the people list on the right shows everyone's availability for the slot you've clicked. Drag a person onto a session, or click a person and then a session. “People × days” turns it round: a row per instructor, a column per day and slot, free slots tinted green." },
      { kind: "sub", text: "The side panel" },
      { kind: "bullets", items: [
        "Click any session to see who's on it (confirmed, unconfirmed, can't make it, this day only), the roles still open and the week's problems for that session.",
        "Add someone: the picker shows their availability for that slot, whether they're cleared to roster, whether their qualifications cover the course type and, for under-18s, the young-worker hours result. On a multi-day course choose “This day only” or “Whole course”.",
        "Remove, or on a multi-day course “skip this day”. A block (Busy, clash, cert, qualification) can be overridden, and the override is recorded.",
        "“Print view” keeps the three printable templates, the PDF and the emergency sheet.",
      ] },
      { kind: "tip", text: "Green dot = Free, amber = Maybe, red = Busy, faint red = hasn't answered (counts as Busy), grey = not asked yet (beyond the availability window)." },
    ],
  },
  {
    id: "rostering",
    icon: "✅",
    label: "Rostering & assigning",
    blurb: "Assign staff with ratio, safety-cover, fit and conflict checks.",
    blocks: [
      { kind: "p", text: "Assign staff from a course (either the card on the Courses page or the course's own page)." },
      { kind: "steps", items: [
        "Pick an instructor. The dropdown shows whether they're cleared (and the reason if not) and whether they're available for this course's times.",
        "Pick their role (e.g. Senior Instructor, Instructor, Safety Boat).",
        "Assign. We check they're qualified, not double-booked, and that the course meets its ratio and safety-cover requirements.",
      ] },
      { kind: "sub", text: "Overrides" },
      { kind: "p", text: "If someone isn't cleared, is unavailable, or would clash, you can still assign them by ticking “assign anyway” and adding a reason. The override is recorded to the audit log with who did it." },
      { kind: "tip", text: "When you pick someone who's unavailable for the course's times, a clear amber note tells you before you commit." },
    ],
  },
  {
    id: "bulk",
    icon: "⚡",
    label: "Bulk assign",
    blurb: "Roster one instructor onto many courses at once.",
    blocks: [
      { kind: "p", text: "On the Courses page, open “Bulk assign staff” to roster the same person across a run of courses in one pass." },
      { kind: "steps", items: [
        "Pick the instructor and the role.",
        "Filter the course list (all / youth / adult / needs cover) and tick the courses — or “select all shown”.",
        "Optionally tick “assign anyway” to override checks (the override is recorded in the change log).",
        "Assign. You get a summary: how many were assigned, how many they were already on, and how many were skipped and why.",
      ] },
      { kind: "tip", text: "Bulk assign runs the same safety checks as a single assignment, and never double-books — a course they're already on is left untouched." },
    ],
  },
  {
    id: "problems",
    icon: "⚠️",
    label: "Problems on the roster",
    blurb: "What contradicts your rules right now, not just at the moment someone was assigned.",
    blocks: [
      { kind: "p", text: "Checks used to run only when you assigned someone. Sessions move, people mark themselves Busy afterwards, leave gets approved, a boat goes into maintenance. The problems list looks at the roster as it stands today and tells you what no longer adds up." },
      { kind: "sub", text: "What it finds" },
      { kind: "bullets", items: [
        "Double-booked: the same instructor on two courses at once (when you check for clashes).",
        "Rostered while Busy or on approved leave, and anyone who hasn't marked a slot Free yet (counts as Busy).",
        "Someone who said they can't make it and still needs replacing.",
        "Not cleared to roster (an expired mandatory check), and qualifications that don't cover the course type.",
        "Young workers' hours and parental permission for under-18s.",
        "Short of instructors or no safety cover (when you flag ratios), and equipment clashes or units in maintenance.",
      ] },
      { kind: "sub", text: "Where you see it" },
      { kind: "bullets", items: [
        "Dashboard: a tile with the count for the next four weeks and the list underneath.",
        "Roster: the week's problems above the roster, and a ⚠ on each affected session.",
        "The morning digest email lists today's problems.",
        "Instructors see their own in the app (rostered while Busy, on leave, or on two courses at once) with a link to fix their availability.",
        "After you move or add a session, the message tells you straight away who it now clashes with.",
      ] },
      { kind: "tip", text: "Red items block rostering (an override was used, or something changed later); amber ones are warnings. Click the course name to sort it out." },
    ],
  },
  {
    id: "rota",
    icon: "🖨️",
    label: "Weekly roster & PDF",
    blurb: "A clean, printable roster for the wall or the inbox.",
    blocks: [
      { kind: "p", text: "The Roster page shows the whole week: each day, each session, who's working, their role, the location/classroom and the times." },
      { kind: "sub", text: "Publish the week" },
      { kind: "steps", items: [
        "Build the week on Courses — add courses and sessions, then put instructors on them. Until you publish, instructors see nothing for that week, so you can move people around freely.",
        "On the Roster page press “Publish week”. Everyone on that week gets a notification (and an email if they allow it) asking them to confirm.",
        "Instructors tap “I'll be there” in the app. If someone can't make it they must say why; you get an email, the course shows “can't make it” and the dashboard counts it under Awaiting confirmation so you can find cover or post an open shift.",
        "Changed something after publishing? Anyone you add, remove or move in a published week is told straight away. “Re-publish & remind everyone” nudges the whole week again.",
      ] },
      { kind: "sub", text: "The PDF" },
      { kind: "p", text: "“Download PDF” on the Roster page produces a proper document, not a picture of the screen. It is a breakdown of each day: a row for every course, with the course name on the left, then its times, then who is working, then any extras you have turned on (number of students booked, location, equipment, staff roles). Pick the period beside the button: one day, the week, or the whole month. The columns, the style (Classic, Bold, Minimal or Compact) and portrait or landscape follow what you chose when you set up, and you can change them any time under Settings → Roster PDF." },
      { kind: "bullets", items: [
        "What goes on it — tick start and finish times, locations, instructors, their roles, and equipment. The course name and date are always there.",
        "Vertical — portrait pages with a table for each day. The classic noticeboard roster.",
        "Horizontal — landscape pages with the days across the top and each session as a small card. Better when you show a lot of detail or run big courses with many staff; a month becomes a calendar grid.",
        "Names — staff appear by first name. If two people on the sheet share a first name, each gets the initial of their surname.",
      ] },
      { kind: "p", text: "On screen, the “Show” tickboxes switch fields on or off and the three on-screen views (by week, by day, compact grid) are remembered on this device; they do not change the PDF." },
      { kind: "bullets", items: [
        "Move between weeks with the navigation — past or future.",
        "Print / Save-as-PDF produces a tidy one-page roster for the wall or the inbox — the layout is designed for it.",
        "Export the week's hours to CSV for payroll straight from the roster.",
        "Unassigned or under-covered sessions (and any missing safety-boat cover) are clearly marked so nothing slips through.",
      ] },
    ],
  },
  {
    id: "young-workers",
    icon: "🧒",
    label: "Young workers' hours",
    blurb: "How rostering checks under-18s against the working-time rules for your country.",
    blocks: [
      { kind: "p", text: "Children and young people can only work limited hours, between set times, with breaks and rest days. The limits differ for 15-year-olds and 16–17-year-olds (the 16–17 rules apply from the 16th birthday), and between term time and school holidays. ActivityRoster carries those figures as a rule pack for each jurisdiction (Great Britain, Northern Ireland and Ireland) and checks every assignment of an under-18 against them. Under-15s are not rostered as workers: they may only volunteer, no hour caps are applied to them, and rostering one who is recorded as employed raises a warning." },
      { kind: "sub", text: "What is checked" },
      { kind: "bullets", items: [
        "Hours in a day and in a week, with the term-time and holiday caps (school-day, Saturday and Sunday caps where they apply).",
        "Earliest start and latest finish.",
        "A break after a set number of hours, daily rest between two working days, and the weekly rest day(s).",
        "Everything already on their roster across all courses counts, so the check looks at the whole week, not just the course you are adding.",
        "Adults (18+) are checked too, as warnings rather than blocks: a week over 48 hours, no 20-minute break on a session longer than 6 hours, less than 11 hours between working days, or seven days in a row. They are warnings because the adult limits are averaged over several weeks and a person can opt out of the 48-hour limit in writing.",
      ] },
      { kind: "sub", text: "What happens when a rule would be broken" },
      { kind: "p", text: "Office → Settings → Young workers' hours lets you choose: block unless an admin overrides with a note (the default; the override and the reason are written to your change log), block outright, or warn only. Whatever you pick, the findings are recorded against the assignment." },
      { kind: "sub", text: "Term dates" },
      { kind: "p", text: "Add your local authority's term dates in Settings. Weeks inside a term use the stricter term-time caps; weeks outside use the holiday caps. If you add no dates, every week is treated as term time, which is the safer assumption." },
      { kind: "sub", text: "The time register" },
      { kind: "p", text: "The weekly roster page has a link to download a young-worker time register (CSV): every session each under-18 was rostered on, with hours, status, any override note, and when it was assigned, confirmed and published. Keep it with your employment records; viewing it is written to your change log." },
      { kind: "sub", text: "Verified and unverified figures" },
      { kind: "p", text: "Each figure in a pack is marked verified once it has been checked against the official source. Until then a warning that depends on it says \"figure not yet verified\", and Settings shows how many figures in your pack are still outstanding. If your centre's jurisdiction has no pack yet, Settings says so plainly and the hour checks do not run; under-18s are still flagged on the Instructors tab." },
      { kind: "tip", text: "This is a planning aid, not legal advice. Child-employment permits, school-leaving dates and local bylaws remain the employer's responsibility; the roster page and Settings say so." },
    ],
  },
  {
    id: "leave",
    icon: "🌴",
    label: "Leave & open shifts",
    blurb: "Approve leave and offer shifts that need cover.",
    blocks: [
      { kind: "p", text: "Staff request leave from their app; you approve or decline from the Leave area, where pending requests are counted on the dashboard." },
      { kind: "bullets", items: [
        "Open shifts let you advertise a session that needs cover; available staff can pick it up.",
        "Approved leave feeds into availability so you don't roster someone who's off.",
      ] },
    ],
  },
  {
    id: "time",
    icon: "⏱️",
    label: "Time & attendance",
    blurb: "Hours from the roster, an optional clock, pay rates and a payroll review you approve before export.",
    blocks: [
      { kind: "p", text: "Hours come from the roster: every session an instructor is on becomes a line on the payroll page automatically, with its scheduled time. Nothing extra to do." },
      { kind: "sub", text: "Pay rates" },
      { kind: "steps", items: [
        "Open an instructor's page → Pay. Choose how they're paid — per hour, per session or per day — and the rate. Volunteers simply have no rate.",
        "Add a different rate for a particular role if you need to (e.g. Senior Instructor days). The role rate wins when they work in that role.",
        "When you change a rate, tick “Apply to unapproved payroll lines from” and pick the date it should count from: every unapproved line from then on takes the new rate. Approved lines always keep the pay they were approved at.",
        "Volunteers have no rate and are hidden from payroll unless you tick “Show volunteers”.",
      ] },
      { kind: "sub", text: "The time clock (optional)" },
      { kind: "p", text: "Settings → Time clock & pay switches on clock in / out in the app. Instructors see the session they're clocking in to; clocking in with no session needs a short note. The office sees who's on the water now, and can step back to any earlier day. Choose whether pay follows the roster or the clock — and change it line by line on the payroll page." },
      { kind: "sub", text: "Payroll review & export" },
      { kind: "steps", items: [
        "Open Payroll. Pick a period (this week, this month, last month, custom dates or all time) and, if you like, one instructor.",
        "Every line shows the rostered time and, where the clock was used, the clocked time side by side. Pick which to pay per line, or use the main switch at the top for the whole period. Any field can be overridden — minutes, pay, a note.",
        "Tick Approve on each line (or Approve all). Approved lines are locked: later roster changes don't touch them. If a session is moved, resized or the person is taken off after approval, the line is flagged “changed” so you can re-check it.",
        "The line above the totals sums the period: people, paid hours, pay, holiday pay, lines needing a rate and lines changed since approval.",
        "Holiday pay: Settings → General can show rolled-up holiday pay (for example 12.07%) as its own column and total for employed and freelance staff; it is never added silently and never applied to volunteers.",
        "Download “Spreadsheet · every shift” or “Spreadsheet · totals” (CSV for Excel or Google Sheets), or print to PDF.",
      ] },
      { kind: "sub", text: "Lunch breaks" },
      { kind: "p", text: "In Settings → Lunch breaks, set a break length, who gets it (anyone working over a number of hours) and whether it's paid. Unpaid breaks come off paid hours; paid breaks are shown but not deducted." },
    ],
  },
  {
    id: "notifications",
    icon: "🔔",
    label: "Notifications",
    blurb: "Keep staff informed by email or in-app.",
    blocks: [
      { kind: "p", text: "Each instructor can choose whether to receive email notifications. In-app notifications keep them up to date with roster changes, leave decisions and shift offers." },
      { kind: "tip", text: "Turn an instructor's email notifications off on their profile if they prefer in-app only." },
    ],
  },
  {
    id: "plans",
    icon: "🏷️",
    label: "Plans & team size",
    blurb: "Flat pricing per centre, and how the team-size limit works.",
    blocks: [
      { kind: "p", text: "ActivityRoster is priced per centre, not per user — one flat price however many people you roster. Pick a plan and move between them whenever you like." },
      { kind: "sub", text: "The plans" },
      { kind: "bullets", items: [
        "Small Club — £35/month. Designed for smaller centres: up to 10 people on your team.",
        "Standard — £65/month. Unlimited instructors and volunteers.",
        "Custom platform (recommended) — from £850 setup, plus £350 travel if we work with your team on site, then £65/month. We build and tailor the whole thing around exactly how your centre runs and hand it over ready to go.",
      ] },
      { kind: "sub", text: "How the Small Club limit works" },
      { kind: "p", text: "On Small Club you can add up to 10 people in total. Everyone counts towards the 10 — paid instructors and volunteers alike. When you try to add the 11th person, we'll let you know you've reached the limit and prompt you to upgrade to Standard for unlimited team members." },
      { kind: "tip", text: "Upgrading is instant and keeps everything you've set up — your courses, staff, certs and roster all stay exactly as they are. Because competitors charge per user, a volunteer-heavy centre usually pays far less with our flat price." },
      { kind: "sub", text: "Fair use on unlimited plans" },
      { kind: "p", text: "Unlimited means your own centre's genuine instructors, staff and volunteers, however many you have. Nothing blocks a centre for its size. If one centre grows past 500 people we'll get in touch to agree the right plan together, and we never cut off access without talking to you first. The full wording is in our Terms under “Fair use on unlimited plans”." },
      { kind: "p", text: "To protect everyone's email delivery, each centre can send up to 200 invitation emails a day. If you invite more in one go (for example a large spreadsheet import), the rest are queued: the staff list shows “Invite goes tomorrow” beside them and they go out automatically the next day. Nothing for you to do." },
    ],
  },
  {
    id: "billing",
    icon: "💳",
    label: "Billing & invoices",
    blurb: "Manage your subscription and get VAT invoices.",
    blocks: [
      { kind: "p", text: "Your centre starts with a free month — no card required. When you're ready, choose monthly or annual (annual works out at one month free on Small Club and two on Standard) and enter card details through secure checkout." },
      { kind: "p", text: "If the trial ends before you choose a plan, nothing is deleted: the centre goes read-only for two weeks (everyone can still look, nobody can change anything), then locks until a plan is chosen. Choosing a plan brings everything straight back. Not ready to choose? Answer the trial-end survey and your centre gets another month free (see “Trial-end survey”)." },
      { kind: "bullets", items: [
        "VAT is handled automatically at checkout for business customers.",
        "After payment you get a proper VAT invoice — downloadable as PDF and emailed to you.",
        "Manage your subscription and download past invoices from the billing area at any time.",
      ] },
    ],
  },
  {
    id: "trial-survey",
    icon: "📝",
    label: "Trial-end survey",
    blurb: "Tell us about your trial and get another month free.",
    blocks: [
      { kind: "p", text: "When your free trial ends without a plan, your centre's admins see a banner in the office and get one email: share your feedback in a short survey and get another month free. Answer the eight questions and your centre unlocks straight away for another 30 days. Nothing you set up during the trial is lost." },
      { kind: "steps", items: [
        "Open the survey from the banner, the email, or Billing (Office → Billing → Take the survey).",
        "Answer the five questions about what's useful, what isn't, what you'd change, what's missing or frustrating, and the one feature you'd add. Each needs at least 30 words; the count under each box turns green when you have enough.",
        "Say how many people would use ActivityRoster at your centre, including admins and instructors, and add any other feedback if you like (that one is optional).",
        "Choose whether we can contact you about your answers. If you choose Yes, check the email shown (it's yours, and you can change it). If you choose No, we won't contact you about them.",
        "Send. Your centre is editable again at once and the new trial end date is shown.",
      ] },
      { kind: "bullets", items: [
        "Only admins can answer, and it's one survey per centre, so the free month is given once.",
        "Your answers go to the ActivityRoster team only, never to your staff, and the extension appears in your change log.",
        "Keep answers about the platform: no names, health details or anything about a child or anyone else.",
      ] },
    ],
  },
  {
    id: "admin-security",
    icon: "🔒",
    label: "Admin & security",
    blurb: "Roles, the 4-digit PIN and the audit trail.",
    blocks: [
      { kind: "p", text: "Lost a phone or left yourself signed in on a shared computer? Office → Security → “Sign out all other devices” ends every other session and forgets every confirmed device, keeping only the one you are using. Your centre also sets how long an idle admin screen waits before asking for the PIN again, under Settings → Security (5 minutes to 4 hours; 30 by default). A full sign-in is always required again after 12 hours away." },
      { kind: "p", text: "Access is authorised on every request: we resolve your account, your centre and your role, and deny anyone who isn't a member." },
      { kind: "sub", text: "Second-factor PIN" },
      { kind: "steps", items: [
        "Each admin sets a 4-digit PIN the first time they sign in.",
        "The PIN is asked for at every login, in addition to the password.",
        "Too many wrong attempts locks the PIN for a cool-off period.",
        "Forgotten it? “Reset it” asks for your password — or emails a one-time code to your account and recovery addresses — before letting you choose a new one. Being signed in isn't enough on its own.",
      ] },
      { kind: "sub", text: "Second step at sign-in (optional)" },
      { kind: "steps", items: [
        "Settings → Security → Second step. Choose an authenticator app (Google Authenticator, 1Password, Authy…) or a code by email, then confirm one code. Save the backup codes somewhere safe.",
        "From then on, signing in with your password asks for the code — sent the way you chose. A backup code gets you in if you've lost the phone or the inbox; each one works once.",
        "Change the method or turn it off any time from the same place; it asks for your password first. Sign-in links still work as before.",
      ] },
      { kind: "sub", text: "New device or country? Password first" },
      { kind: "bullets", items: [
        "The first time you use a new device, or the same device from a new country, you're asked for your password before the PIN — even though you're already signed in. Accounts without a password get a one-time code by email instead. Switching between Wi-Fi and mobile data doesn't trigger it.",
        "Once confirmed, that device isn't asked again for 90 days. Your confirmed devices are listed under Security, with a “Forget all devices” button if a device is lost.",
        "A stolen session or a left-open laptop can't be used from somewhere new without the password.",
      ] },
      { kind: "sub", text: "Know when something changes" },
      { kind: "bullets", items: [
        "Every PIN set or reset, lock-out, recovery-email change and password reset is recorded with the device, country and IP it came from.",
        "You get an email each time — to your account address and your recovery address — so an intruder can't act quietly.",
        "Resetting your password signs out every other device.",
        "See the last few events under Security → Recent security activity.",
      ] },
      { kind: "sub", text: "Audit trail" },
      { kind: "p", text: "Every roster, resource, settings and billing change is written to an audit log — including who made an override and why." },
    ],
  },
  {
    id: "data",
    icon: "🛡️",
    label: "Data, privacy & export",
    blurb: "Hosted on Cloudflare in the EU, UK GDPR-ready, and yours to export.",
    blocks: [
      { kind: "p", text: "Your data is pinned to the EU for GDPR, with PII scrubbing on error monitoring. Each centre's data is structurally isolated — it can never be read alongside another centre's." },
      { kind: "bullets", items: [
        "Export your centre's data at any time (Settings → Data & account).",
        "If a centre is ever suspended, it can still export within the retention window before deletion.",
        "Anything you can't take back — a full export, one person's export, an anonymisation — asks for your 4-digit PIN again first. It's remembered for ten minutes on that sign-in only.",
      ] },
      { kind: "sub", text: "When a staff member asks about their data" },
      { kind: "p", text: "Open their profile and use the Data & privacy card. You are the data controller for your staff; these tools let you answer a request yourself, within the month the law allows." },
      { kind: "bullets", items: [
        "Copy of their data — download everything the centre holds about them as JSON or CSV. Each download is recorded in the change log.",
        "Correct — edit the profile as usual; every change is recorded.",
        "Restrict processing — keeps the record but stops it being used: they cannot be rostered and get no notifications until you lift it. Give a reason; it goes in the change log.",
        "Anonymise (erasure) — removes everything identifying, their certificates and files, availability, leave, pay rates, notifications and their login. Roster and payroll history stays as “Former staff member”. Type their name to confirm; it cannot be undone, and it is re-applied automatically if the database is ever restored from a backup.",
      ] },
      { kind: "sub", text: "Your change log" },
      { kind: "p", text: "Office → Change log lists every change and every sign-in event on your centre's accounts. Download CSV gives you the last 90 days; add ?from=YYYY-MM-DD&to=YYYY-MM-DD to the link for another period." },
    ],
  },
  {
    id: "retention",
    icon: "🗓️",
    label: "Data retention",
    blurb: "How long records are kept, and the 14-day notice before anything goes.",
    blocks: [
      { kind: "p", text: "Office → Settings → Data retention sets how many months each kind of record is kept: former staff profiles, leave requests, availability, notifications, clock and payroll records, and the change log. The defaults follow our published retention schedule; statutory minimums (6 years for payroll, 3 for the change log) cannot be shortened." },
      { kind: "sub", text: "What happens" },
      { kind: "steps", items: [
        "Once a day the system looks for records past their period.",
        "Every admin is emailed a list of what will go, with 14 days' notice. Nothing has gone yet at that point.",
        "A former staff member's profile shows the date and a “Keep for another N months” button, which restarts their clock.",
        "When the 14 days are up, the records are removed. People are anonymised rather than deleted: roster and payroll history stays as “Former staff member”, everything identifying goes.",
        "Each run is written to your change log, and re-applied automatically if the database is ever restored from a backup.",
      ] },
      { kind: "tip", text: "Need something kept longer for a legal reason, such as an incident report? Lengthen the period here and note why in your own records." },
    ],
  },
  {
    id: "help-assistant",
    icon: "💬",
    label: "The Help button",
    blurb: "Ask a question in your own words and get the answer from these guides.",
    blocks: [
      { kind: "p", text: "Every page in the office, and every page of this website, has a small Help button in the bottom-right corner. Press it, type a question such as “How do I publish the roster?”, and it answers with the right passage from the Learning Centre, plus a link to the full guide." },
      { kind: "sub", text: "Using it" },
      { kind: "steps", items: [
        "Press Help in the bottom-right corner. It opens a small panel so you can keep working.",
        "Type your question, or tap one of the suggested questions. The suggestions change with the page you are on.",
        "Read the answer. “Read the guide” opens the whole section; “Also see” links to related guides.",
        "Press the arrows icon to make the panel bigger (on a phone it fills the screen), and the cross or Esc to close it. “Clear” starts a fresh conversation.",
      ] },
      { kind: "sub", text: "What it is, and what it isn't" },
      { kind: "bullets", items: [
        "It is not AI. It searches the guides and setup answers we have written, so it never makes things up and never sees your centre's data.",
        "If nothing fits, it says so and points you to the closest guides and to hello@activityroster.com.",
        "The conversation stays in your browser tab and is gone when you close it.",
      ] },
      { kind: "sub", text: "What we keep" },
      { kind: "p", text: "When an office user asks a question inside their centre, we keep the question, the page it was asked on and which guide answered it, for 30 days, so we can see what the guides are missing and improve them. We never keep the answer or the name of the person who asked. Questions typed on the public website are not stored at all." },
    ],
  },
  {
    id: "feature-requests",
    icon: "💡",
    label: "Requests & ideas",
    blurb: "Ask for a feature or report a problem, follow it to Live, and back what other centres need.",
    blocks: [
      { kind: "p", text: "ActivityRoster is a live platform that keeps improving, and what we build next comes from centres. Open Requests & ideas from the sidebar (or the tile at the top of Settings) to ask for a new feature, suggest a change or tell us about something that isn't working." },
      { kind: "sub", text: "Sending a request" },
      { kind: "steps", items: [
        "Choose whether it's a new feature or something not working right.",
        "Say what problem you're trying to solve: what happens now, and what it stops you doing. For a fault, say what you did, what you expected and what happened instead.",
        "Say what you'd like us to add or change, and how it would work for you.",
        "If you can, add who it affects, how often it comes up, how you get round it today and how much it matters. The more detail, the quicker we can understand and build it.",
        "Sum it up in a short title, add a screenshot if it helps, tick the box to agree the title can be shown to other centres, and press Send request.",
      ] },
      { kind: "tip", text: "Write it as you'd explain it to a new member of staff. A clear brief is far more likely to be built quickly than a one-liner." },
      { kind: "sub", text: "What other centres see" },
      { kind: "bullets", items: [
        "Only the title, its stage and how many centres need it. Never the details, the screenshot, who sent it or which centre it came from.",
        "Nothing at all until we've read it: a new request stays in Submitted, visible only to your centre and the ActivityRoster team. We may tidy the title before it goes on the board.",
        "Screenshots stay private to your centre and us. Before attaching one, crop or cover anything personal: names, phone numbers, emails, addresses, and especially anything about children or young staff.",
      ] },
      { kind: "sub", text: "The stages" },
      { kind: "bullets", items: [
        "Submitted: we have it, and nobody else can see it yet.",
        "In review: we're working out whether and how it can be done. It's on the shared board now.",
        "Approved, In development, Testing: we're building it.",
        "Live: the change is in the platform.",
        "Not possible: we looked and can't do it, at least for now. We'll leave a note under My requests saying why where we can.",
      ] },
      { kind: "p", text: "We read every request and look into whether the change is possible. We can't promise to build everything, but if it's possible and it helps centres, we'll do it. Each time a request moves on, the person who sent it gets an email." },
      { kind: "sub", text: "We need this too" },
      { kind: "p", text: "Below your own requests is the board of everything centres have asked for. Press We need this too on the ones that would help your centre (press again to take it back). Only the count is shown, never which centres voted, and the most-needed requests go to the top of each stage. We build around what centres vote for." },
    ],
  },
  {
    id: "if-the-platform-is-down",
    icon: "🛟",
    label: "If the platform is down",
    blurb: "Two fallbacks so a session can still run safely without us.",
    blocks: [
      { kind: "p", text: "Boats go out whether or not the internet is working. Two things make sure you always have today's plan on paper." },
      { kind: "sub", text: "The emergency sheet" },
      { kind: "p", text: "From the roster, press Emergency sheet. It lists today's sessions, who is on each one, their phone number and their emergency contact (and guardian, for under-18s). Print it or save it as a PDF for the duty officer or safety boat, and shred it at the end of the day. Only admins can open it, and each time it is opened is written to your change log. Students aren't recorded in ActivityRoster, so keep your own booking list alongside it." },
      { kind: "sub", text: "The morning roster email" },
      { kind: "p", text: "In Office → Settings, switch on \"Email every admin the day's roster each morning\" and pick the hour. Every admin gets today's sessions, who is on them and where, with a link to the printable roster. It's off by default; we recommend it in season." },
      { kind: "tip", text: "Print tomorrow's emergency sheet the evening before if your signal on the water is poor." },
    ],
  },
];

/**
 * The order a centre meets the guides in: from never having used the platform
 * (set up, courses, instructors, the roster) to running the season, then the
 * account and data topics, with help and troubleshooting last. SECTIONS is kept
 * in the same order; the Learning Centre shows these as headings.
 */
export const GUIDE_STAGES: { label: string; ids: string[] }[] = [
  { label: "Set up your centre", ids: ["getting-started", "settings", "locations", "equipment"] },
  { label: "Add your courses", ids: ["courses", "import", "integrations"] },
  { label: "Add your instructors", ids: ["staff", "staff-import", "roles", "licences", "app"] },
  { label: "Build the roster", ids: ["availability", "office-managed", "dashboard", "board", "rostering", "bulk", "problems", "rota"] },
  { label: "Run the season", ids: ["young-workers", "leave", "time", "notifications"] },
  { label: "Account, billing & data", ids: ["plans", "billing", "trial-survey", "admin-security", "data", "retention"] },
  { label: "Help & troubleshooting", ids: ["help-assistant", "feature-requests", "if-the-platform-is-down"] },
];
