/**
 * Short answers to the questions people ask while setting up, each pointing at
 * the Learning Centre section with the full story. Written from the guides
 * (lib/learn/sections); keep them in step when a feature changes. `ask` holds
 * a few ways people phrase the question, which helps the search match.
 */
export interface FaqEntry {
  id: string;
  ask: string[];
  answer: string;
  topic: string;
}

export const FAQ: FaqEntry[] = [
  { id: "setup", topic: "getting-started", ask: ["How does setup work?", "how do I get started", "set up my account", "first steps", "onboarding"],
    answer: "Sign up and a short wizard sets your centre up in a few minutes: choose the features you want, tick the RYA courses you run, add your team (they get an invite), and pick how your printable roster looks. You can skip any step and finish later from the dashboard checklist." },
  { id: "add-staff", topic: "staff", ask: ["How do I add instructors?", "add staff", "add a new instructor", "invite my team", "invite instructors", "invite new staff"],
    answer: "Go to Instructors → Add instructors. Quick add takes a name and email and sends the invite (tick “Send the invite”), so they fill in their own details and certificates when they accept it. Paste a list adds several people at once (one per line). Open “Add with all details” to set courses, licences and checks yourself." },
  { id: "import-staff", topic: "staff-import", ask: ["Can I import staff from a spreadsheet?", "import staff from a spreadsheet", "upload a list of instructors", "CSV of staff"],
    answer: "Instructors → Import from spreadsheet. Upload a CSV or Excel file, check each row (names, emails, flags), tick “email a portal invite” if you want, then import. A sheet of just names and emails is enough to start." },
  { id: "invite-not-arrived", topic: "staff", ask: ["What if an instructor didn't get the invite?", "instructor didn't get the invite", "resend invite", "invite expired", "invite pending", "invite not received"],
    answer: "On the Instructors list, press “Re-send invite” next to the person. The badge shows how long ago the last one went (“Invited 3 days ago”). The link in the email works once for a short while; if it has expired they can go to your centre's sign-in page, enter their email and choose “Email me a sign-in link”. One reminder goes automatically a day later." },
  { id: "create-course", topic: "courses", ask: ["How do I create a course?", "add a course", "set up a course", "make a new course"],
    answer: "Open Courses. Use the planner at the top: give the course a name, pick the course type (this sets the RYA scheme, ratios and safety cover), add sessions by clicking days in the calendar, and press “Create course”. Locations, kit and who's needed can be set under “More options” or changed later on the course page." },
  { id: "import-courses", topic: "import", ask: ["Can I import my courses?", "import courses", "bring in my bookings", "upload my course calendar", "import my roster from a spreadsheet", "spreadsheet of courses", "import the rota"],
    answer: "Courses → Import. Upload a spreadsheet or a calendar file, review the rows, correct anything that didn't match, then import. If you use a booking system, Integrations can pull courses in from its calendar feed." },
  { id: "booking-system", topic: "integrations", ask: ["How do I connect my booking system?", "connect my booking system", "integrate bookings", "calendar feed", "iCal link"],
    answer: "Courses → Integrations. Pick your booking system and paste its calendar (iCal) feed address; the guide lists where each system keeps it. Use “Check for updates” to pull in changes." },
  { id: "assign", topic: "rostering", ask: ["How do I roster someone?", "assign an instructor", "put staff on a course", "add someone to a course"],
    answer: "Open the course (or use the roster board) and pick a person for each role. The picker shows who is free, qualified and clear of clashes. If someone isn't, you can still assign them with a note saying why; it's recorded." },
  { id: "board", topic: "board", ask: ["How does the roster board work?", "roster board", "drag and drop staff", "plan the week"],
    answer: "Roster → Board shows each day's courses with their open roles. Drag people from the side list onto a course, or switch to the people × days layout. Problems show on each card." },
  { id: "one-day", topic: "courses", ask: ["Can someone cover just one day of a course?", "different instructor on one day", "change staff for a single day", "multi-day course different staff"],
    answer: "People are on the whole course by default. On the course page, each session lets you take someone off that day or add someone for that day only; the rest of the course stays as it is." },
  { id: "publish", topic: "rota", ask: ["How do I publish the roster?", "publish the roster", "send the rota to staff", "how do staff see their shifts", "publish week"],
    answer: "On the Roster page, press Publish for the week. Staff see published weeks in the app and are notified; until then the week is a draft only the office sees." },
  { id: "pdf", topic: "rota", ask: ["How do I print the roster?", "print the roster", "roster PDF", "download the rota"],
    answer: "Roster → PDF prints or downloads the week (or a day) in your chosen style. Settings → Roster PDF sets the layout." },
  { id: "office-admin", topic: "roles", ask: ["How do I add another office admin?", "add another admin", "give someone office access", "second administrator", "office admin permissions"],
    answer: "Only the superadmin can do this: Instructors → Office access → invite them, then tick which parts of the office they can reach (Roster & courses, Staff, Emergency & guardian contacts, Payroll, Settings, Billing, Exports). A new office admin starts with nothing ticked." },
  { id: "app", topic: "app", ask: ["How do instructors use the app?", "instructor app", "how do instructors join", "company code", "download the app"],
    answer: "Instructors can join from an invite, or download the app and enter your company code (Settings → General → Company code); you then approve them on the Instructors page. In the app they see their shifts, set availability, confirm sessions and upload certificates." },
  { id: "availability", topic: "availability", ask: ["How does availability work?", "how does availability work", "staff availability", "mark free busy", "usual week"],
    answer: "Instructors mark each slot Free, Maybe or Busy in the app; anything not answered counts as Busy inside your availability window. They can set a usual week and add a note per day. The office can enter availability for someone too (useful for volunteers)." },
  { id: "pay", topic: "time", ask: ["How do I set pay rates?", "set pay rates", "payroll", "how is pay worked out", "hourly rate"],
    answer: "Settings → Pay rates: set the standard rate for each role (per hour, session or day), then give anyone paid differently their own rate, or a rate for particular courses. Their own rate can also be set on their staff page. Hours come from the roster: every session someone is on becomes a payroll line. Review, adjust and approve lines on the Payroll page, then export." },
  { id: "holiday-pay", topic: "settings", ask: ["How is holiday pay worked out?", "holiday pay", "12.07%", "rolled up holiday"],
    answer: "Settings → General: set the holiday pay percentage (UK casual workers: 12.07%). It shows as its own column on payroll for employed and freelance staff, never for volunteers." },
  { id: "under-18", topic: "young-workers", ask: ["How do under-18 instructors work?", "under 18 instructors", "young workers hours", "child employment rules", "16 year old instructor"],
    answer: "Add each person's date of birth; under-18s are flagged automatically. Rostering then checks their hour, rest and start/finish rules for your country, and Settings → Young workers sets whether a breach is blocked or warned. Add your local term dates for the term-time limits." },
  { id: "parent", topic: "roles", ask: ["How does parent approval work?", "parent approval", "parental permission", "guardian consent"],
    answer: "When an under-18 signs up, they give a parent's email; the parent approves from their own small account. Until then the office can't roster them without an override. Settings → Young workers can make this optional." },
  { id: "certs", topic: "licences", ask: ["How do I track certificates?", "certificates", "DBS check", "first aid expiry", "track qualifications"],
    answer: "Each instructor has a documents area for qualifications and checks. Anything expiring within your warning period is flagged on the dashboard and staff list. Vetting checks (DBS, PVG and so on) record the status and dates only; the certificate itself is never uploaded." },
  { id: "equipment", topic: "equipment", ask: ["How do I add boats and equipment?", "add boats", "equipment", "track kit", "maintenance"],
    answer: "Equipment: add your types (e.g. Pico, RIB) with how many you have, and individual units for tracked kit. Attach kit to a course from its page. Clashes, shortages and kit in maintenance show on the problems list." },
  { id: "kit-rules", topic: "equipment", ask: ["What are kit rules?", "kit rules", "automatic equipment for courses", "one boat per two students"],
    answer: "Course setup → Kit rules lets you say what each course type needs (fixed, or per so many students). They're off until you tick Settings → Checks when rostering → “Use kit rules”; then new courses get that kit automatically." },
  { id: "locations", topic: "locations", ask: ["How do I add locations?", "set up locations at my centre", "location categories", "add locations", "areas", "where courses run"],
    answer: "Locations: add categories (e.g. Lake, Classroom) and the places within them. Pick locations when creating a course, or change them later on the course page." },
  { id: "cancel", topic: "courses", ask: ["How do I cancel a course?", "cancel a course", "weather cancellation", "cancel a session"],
    answer: "On the course, choose Cancel (the whole course or one day). Say why and pick the pay rule (no pay, paid as rostered, or a cancellation fee). It leaves the roster, PDF and app, and everyone rostered is told. Cancelled days can be restored." },
  { id: "leave", topic: "leave", ask: ["How do holiday requests work?", "holiday requests", "leave", "open shifts", "cover"],
    answer: "Instructors request leave in the app; you approve it under Leave & cover, and approved leave counts as Busy. Open shifts let you offer a session to volunteers to claim." },
  { id: "problems", topic: "problems", ask: ["What are problems on the roster?", "what are problems", "why is something flagged", "double booked warning"],
    answer: "The problems list checks the roster continuously: double-bookings, people rostered while Busy or on leave, missing qualifications, uncovered sessions and equipment issues. It shows on the dashboard, the roster and the morning email." },
  { id: "checks", topic: "settings", ask: ["Can I turn off a roster check?", "turn off double booking check", "rostering checks", "stop blocking"],
    answer: "Settings → General → Checks when rostering. Each check (certs, ratios, double-booking, availability, equipment quantities) can be switched on or off; you'll be asked to confirm before switching one off." },
  { id: "pin", topic: "admin-security", ask: ["I forgot my PIN. What now?", "forgot my PIN", "reset PIN", "change PIN", "two factor"],
    answer: "On the PIN screen, choose “Forgot PIN” and we email a reset code. To change it, go to Settings → Data & account → Change login PIN. Two-step sign-in is under Security & 2FA." },
  { id: "plans", topic: "plans", ask: ["How much does it cost?", "pricing", "how much does it cost", "change plan", "team size limit"],
    answer: "ActivityRoster is priced per centre, not per user. The Plans & team size guide explains each plan and its limits; change plan from Billing in the office menu." },
  { id: "trial", topic: "billing", ask: ["Is there a free trial?", "free trail", "free trial", "what happens when the trial ends", "card required"],
    answer: "The first month is free with no card. If it ends before you choose a plan, nothing is deleted: the centre goes read-only until you pick one. Answering the short trial-end survey earns another free month." },
  { id: "fair-use", topic: "plans", ask: ["Is unlimited really unlimited?", "fair use", "is there a limit on staff", "how many people can I add", "invite goes tomorrow", "invite limit"],
    answer: "On Standard there is no limit: it covers all your own centre's instructors, staff and volunteers, and nothing blocks a centre for its size. Above 500 people we'd get in touch to agree the right plan together. Each centre can send up to 200 invitation emails a day; any more are queued and go out automatically the next day (the staff list shows “Invite goes tomorrow”)." },
  { id: "export", topic: "data", ask: ["How do I export my data?", "export my data", "download everything", "delete my data", "GDPR"],
    answer: "Settings → Data & account → Export all data (JSON) downloads the whole centre (you'll be asked for your PIN). Individuals can be exported, restricted or anonymised from their profile under Data & privacy." },
  { id: "down", topic: "if-the-platform-is-down", ask: ["What if the platform is down?", "platform is down", "no internet", "emergency sheet", "offline"],
    answer: "Print the emergency sheet from the Roster page (today's staff with emergency contacts), switch on the morning roster email in Settings, and instructors' app keeps their next seven days offline." },
  { id: "human", topic: "getting-started", ask: ["How do I talk to a person?", "talk to someone", "contact support", "speak to a person", "email support"],
    answer: "Email hello@activityroster.com and we'll get back to you, usually the same working day." },
  { id: "password", topic: "getting-started", ask: ["I forgot my password. What now?", "forgot my password", "change my password", "reset password", "set a password", "new password"],
    answer: "On your centre's sign-in page, enter your email and tap “Forgot password?”. We email a link to set a new password (at least 8 characters). The same link works if you simply want to change it, or if you've only ever signed in with emailed links." },
  { id: "two-factor", topic: "admin-security", ask: ["How do I turn on two-factor?", "turn on two-factor", "two factor authentication", "2FA", "authenticator app", "backup codes"],
    answer: "Settings → Security → Second step. Choose an authenticator app (Google Authenticator, 1Password, Authy…) or a code by email, confirm one code, and save the backup codes somewhere safe. From then on, signing in with your password asks for the code." },
  { id: "who-sees", topic: "roles", ask: ["Who can see payroll and contacts?", "who can see payroll", "who can see emergency contacts", "who has access to staff documents", "restrict what an admin can see", "limit office access"],
    answer: "Sensitive pages (payroll, certificates and documents, emergency and guardian contacts, the emergency sheet and the whole-centre export) show a line naming who can open them. The superadmin changes it under Instructors → Office access by ticking which parts each office admin can reach." },
  { id: "help-ai", topic: "help-assistant", ask: ["Is this AI?", "are you a bot", "are you a chatbot", "do you store my questions", "who sees my questions"],
    answer: "No AI here: I search the Learning Centre guides and setup answers ActivityRoster has written. Inside a centre's office we keep the question (not the answer or your name) for 30 days to improve the guides; nothing typed on the public website is stored." },
];
